import { resolve, relative } from 'node:path';
import type {
  AppDslV1,
  GenerationArtifact,
  GenerationArtifactResult,
  GenerationPlanV1,
  GenerationArtifactType
} from '../types/app-dsl';
import { writeJsonFile, writeTextFile } from '../utils/fs';

export interface BuildPlanOptions {
  baseOutDir: string;
  appFolderName?: string;
}

export interface GenerateArtifactsResult {
  plan: GenerationPlanV1;
  artifacts: GenerationArtifactResult[];
  appOutDir: string;
}

export function resolveOutRoot(cwd: string, requestedOut?: string): string {
  const base = resolve(cwd, 'out');
  const target = resolve(base, requestedOut ?? '.');
  if (!target.startsWith(base)) {
    throw new Error('out path must stay inside ./out');
  }
  return target;
}

export function buildGenerationPlan(dsl: AppDslV1, options: BuildPlanOptions): GenerationPlanV1 {
  const appFolder = sanitizePathSegment(options.appFolderName ?? dsl.app.id);
  const outputs = outputSpecs().map((spec) => ({
    type: spec.type,
    relativePath: relative(options.baseOutDir, resolve(options.baseOutDir, appFolder, spec.relativePath)).replace(/\\/g, '/')
  }));

  return {
    version: 'generation-plan.v1',
    appId: dsl.app.id,
    dslVersion: dsl.version,
    inputHash: `fnv1a-${fnv1a(stableStringify(dsl)).toString(16)}`,
    generatedAt: new Date().toISOString(),
    outputs
  };
}

export async function generateArtifacts(
  dsl: AppDslV1,
  outRoot: string,
  writeFiles: boolean
): Promise<GenerateArtifactsResult> {
  const appFolder = sanitizePathSegment(dsl.app.id);
  const appOutDir = resolve(outRoot, appFolder);
  const plan = buildGenerationPlan(dsl, { baseOutDir: outRoot, appFolderName: appFolder });
  const artifacts = buildArtifacts(dsl);

  await writeJsonFile(resolve(appOutDir, 'plan.json'), plan);

  const results: GenerationArtifactResult[] = [];
  for (const artifact of artifacts) {
    const relativePath = `${appFolder}/${artifact.relativePath}`;
    if (writeFiles) {
      await writeArtifact(resolve(outRoot, relativePath), artifact);
    }
    results.push({
      type: artifact.type,
      relativePath,
      written: writeFiles
    });
  }

  return {
    plan,
    artifacts: results,
    appOutDir
  };
}

function writeArtifact(path: string, artifact: GenerationArtifact): Promise<void> {
  if (artifact.contentType === 'json') {
    return writeJsonFile(path, artifact.content);
  }
  return writeTextFile(path, String(artifact.content));
}

function buildArtifacts(dsl: AppDslV1): GenerationArtifact[] {
  return [buildDbArtifact(dsl), buildApiArtifact(dsl), buildPermArtifact(dsl), buildPageArtifact(dsl)];
}

function buildDbArtifact(dsl: AppDslV1): GenerationArtifact {
  const schemaName = `app_${sanitizeSqlIdentifier(dsl.app.id)}`;
  const rows = dsl.resources
    .map(
      (resource) =>
        `('${escapeSql(resource.id)}', '${escapeSql(resource.method)}', '${escapeSql(resource.endpoint)}')`
    )
    .join(',\n  ');

  const sql = `-- generated by meta-lc-cli\nCREATE SCHEMA IF NOT EXISTS ${schemaName};\n\nCREATE TABLE IF NOT EXISTS ${schemaName}.generated_resources (\n  id TEXT PRIMARY KEY,\n  method TEXT NOT NULL,\n  endpoint TEXT NOT NULL\n);\n\nINSERT INTO ${schemaName}.generated_resources (id, method, endpoint) VALUES\n  ${rows}\nON CONFLICT (id) DO UPDATE\nSET method = EXCLUDED.method, endpoint = EXCLUDED.endpoint;\n`;

  return {
    type: 'db',
    relativePath: 'db/up.sql',
    contentType: 'text',
    content: sql
  };
}

function buildApiArtifact(dsl: AppDslV1): GenerationArtifact {
  const openapi = {
    openapi: '3.0.3',
    info: {
      title: `${dsl.app.name} API`,
      version: dsl.app.version
    },
    paths: {
      '/query': {
        post: {
          summary: 'Query endpoint',
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/QueryRequest' }
              }
            }
          },
          responses: {
            '200': {
              description: 'Query response',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/QueryResponse' }
                }
              }
            }
          }
        }
      },
      '/mutation': {
        post: {
          summary: 'Mutation endpoint',
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/MutationRequest' }
              }
            }
          },
          responses: {
            '200': {
              description: 'Mutation response',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/MutationResponse' }
                }
              }
            }
          }
        }
      }
    },
    components: {
      schemas: {
        QueryRequest: {
          type: 'object',
          properties: {
            resources: { type: 'array', items: { type: 'string', enum: dsl.resources.map((item) => item.id) } }
          }
        },
        QueryResponse: {
          type: 'object',
          properties: {
            rows: { type: 'array', items: { type: 'object' } }
          }
        },
        MutationRequest: {
          type: 'object',
          properties: {
            action: { type: 'string' }
          }
        },
        MutationResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean' }
          }
        }
      }
    }
  };

  return {
    type: 'api',
    relativePath: 'api/openapi.json',
    contentType: 'json',
    content: openapi
  };
}

function buildPermArtifact(dsl: AppDslV1): GenerationArtifact {
  const permission = {
    appId: dsl.app.id,
    generatedAt: new Date().toISOString(),
    roles: dsl.roles.map((role) => ({
      id: role.id,
      name: role.name,
      scopes: role.scopes
    }))
  };

  return {
    type: 'perm',
    relativePath: 'perm/permission.json',
    contentType: 'json',
    content: permission
  };
}

function buildPageArtifact(dsl: AppDslV1): GenerationArtifact {
  const pageDsl = {
    appId: dsl.app.id,
    pages: dsl.pages.map((page) => ({
      id: page.id,
      title: page.title,
      route: page.route,
      resources: page.resources
    })),
    resources: dsl.resources.map((resource) => ({
      id: resource.id,
      method: resource.method,
      endpoint: resource.endpoint
    }))
  };

  return {
    type: 'page',
    relativePath: 'page/page.dsl.json',
    contentType: 'json',
    content: pageDsl
  };
}

function outputSpecs(): Array<{ type: GenerationArtifactType; relativePath: string }> {
  return [
    { type: 'db', relativePath: 'db/up.sql' },
    { type: 'api', relativePath: 'api/openapi.json' },
    { type: 'perm', relativePath: 'perm/permission.json' },
    { type: 'page', relativePath: 'page/page.dsl.json' }
  ];
}

function stableStringify(input: unknown): string {
  return JSON.stringify(sortKeys(input));
}

function sortKeys(input: unknown): unknown {
  if (Array.isArray(input)) {
    return input.map((item) => sortKeys(item));
  }
  if (input && typeof input === 'object') {
    return Object.keys(input as Record<string, unknown>)
      .sort()
      .reduce<Record<string, unknown>>((acc, key) => {
        acc[key] = sortKeys((input as Record<string, unknown>)[key]);
        return acc;
      }, {});
  }
  return input;
}

function fnv1a(text: string): number {
  let hash = 0x811c9dc5;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash += (hash << 1) + (hash << 4) + (hash << 7) + (hash << 8) + (hash << 24);
  }
  return hash >>> 0;
}

function sanitizePathSegment(value: string): string {
  return value.replace(/[^a-zA-Z0-9_-]/g, '_') || 'app';
}

function sanitizeSqlIdentifier(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9_]/g, '_') || 'app';
}

function escapeSql(value: string): string {
  return value.replace(/'/g, "''");
}
